name: Deploy Forge Images
on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.16, 1.19, latest]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build, Tag, and Push ${{ matrix.version }} Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/forge:${{ matrix.version }} -f ${{ matrix.version }}.Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/forge:${{ matrix.version }}